import assert from "node:assert/strict";
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { test } from "node:test";
import { BRAND } from "../src/brand.js";
import { COMMANDS } from "../src/commands.js";
import {
  mermaidInit,
  normalizeMermaid,
  renderCommandsTable,
  renderDocs,
  renderGroupsTable,
  renderMcpToolsTable,
  renderRepoMap,
  spliceBlock,
  updateCounts,
} from "../src/docs_render.js";
import { TOOLS } from "../src/mcp_tools.js";

const dir = () => mkdtempSync(join(tmpdir(), "forge-render-"));

test("renderCommandsTable names every command exactly as the docs check requires", () => {
  const table = renderCommandsTable();
  for (const name of Object.keys(COMMANDS))
    assert.ok(
      new RegExp(`\\b${BRAND.cli} ${name}\\b`).test(table),
      `table carries \`${BRAND.cli} ${name}\``,
    );
});

test("renderGroupsTable and renderMcpToolsTable derive fully from their registries", () => {
  const groups = renderGroupsTable();
  assert.ok(groups.includes("**Labs (experimental)**"), "group labels come from GROUPS keys");
  const tools = renderMcpToolsTable();
  for (const t of TOOLS) assert.ok(tools.includes(`\`${t.name}\``), `tool row for ${t.name}`);
});

test("mermaidInit carries the two brand identity hexes the diagram check enforces", () => {
  const init = mermaidInit();
  const d = BRAND.colors.dark;
  assert.ok(init.includes("%%{init"), "is an init directive");
  assert.ok(init.toLowerCase().includes(d.brand.toLowerCase()), "ember accent present");
  assert.ok(init.toLowerCase().includes(d.bg.toLowerCase()), "warm-black canvas present");
});

test("spliceBlock replaces only the managed span and is idempotent", () => {
  const begin = `<!-- forge:render:x:begin (generated by \`${BRAND.cli} docs render\` — do not edit) -->`;
  const doc = `prose before\n\n${begin}\nOLD\n<!-- forge:render:x:end -->\n\nprose after`;
  const r1 = spliceBlock(doc, "x", "NEW");
  assert.ok(r1.found && r1.changed, "first splice replaces");
  assert.ok(r1.text.includes("NEW") && !r1.text.includes("OLD"));
  assert.ok(r1.text.startsWith("prose before") && r1.text.endsWith("prose after"));
  const r2 = spliceBlock(r1.text, "x", "NEW");
  assert.ok(r2.found && !r2.changed, "same body → no change");
  assert.equal(spliceBlock(doc, "missing", "NEW").found, false, "unknown block untouched");
});

test("updateCounts rewrites any stale N-MCP-tools phrase to the registry count", () => {
  const out = updateCounts("we ship 3 MCP tools today and 999 MCP tools tomorrow");
  assert.equal(
    out,
    `we ship ${TOOLS.length} MCP tools today and ${TOOLS.length} MCP tools tomorrow`,
  );
});

test("normalizeMermaid unifies init lines, skips ignored examples and init-less blocks", () => {
  const old =
    "%%{init: {'theme':'base','themeVariables':{'lineColor':'#f26430','tertiaryColor':'#171310'}}}%%";
  const themed = `\`\`\`mermaid\n${old}\nflowchart LR\n  a --> b\n\`\`\``;
  assert.ok(
    normalizeMermaid(themed).includes(mermaidInit()),
    "old init upgraded to the shared theme",
  );
  const ignored = `<!-- docs-check-ignore -->\n\`\`\`mermaid\n${old}\nflowchart LR\n  a --> b\n\`\`\``;
  assert.equal(normalizeMermaid(ignored), ignored, "opted-out example blocks stay untouched");
  const bare = "```mermaid\nflowchart LR\n  a --> b\n```";
  assert.equal(normalizeMermaid(bare), bare, "no init line → left for the diagram check to flag");
});

test("renderRepoMap draws directories and import edges from the real tree", () => {
  const root = dir();
  mkdirSync(join(root, "app"));
  mkdirSync(join(root, "lib"));
  writeFileSync(join(root, "app", "main.js"), 'import "../lib/util.js";\n');
  writeFileSync(join(root, "lib", "util.js"), "export const u = 1;\n");
  const map = renderRepoMap(root);
  assert.ok(map.startsWith("```mermaid"), "is a mermaid fence");
  assert.ok(map.includes(mermaidInit()), "uses the shared brand theme");
  assert.ok(map.includes('app["app<br/>1 file"]') && map.includes('lib["lib<br/>1 file"]'));
  assert.ok(map.includes("app --> lib"), "the import edge points importer → imported");
});

test("renderDocs fills managed blocks, is idempotent, and reports tampering as strict drift", () => {
  const root = dir();
  const begin = `<!-- forge:render:commands-table:begin (generated by \`${BRAND.cli} docs render\` — do not edit) -->`;
  writeFileSync(
    join(root, "README.md"),
    `# fixture\n\n${begin}\n<!-- forge:render:commands-table:end -->\n`,
  );
  const first = renderDocs(root, { write: true });
  assert.ok(first.files.some((f) => f.file === "README.md" && f.changed && f.strict));
  assert.ok(readFileSync(join(root, "README.md"), "utf8").includes(`\`${BRAND.cli} rank\``));
  const second = renderDocs(root, { write: false });
  assert.equal(second.files.length, 0, "freshly rendered → nothing to report");
  assert.ok(second.ok);
  writeFileSync(
    join(root, "README.md"),
    readFileSync(join(root, "README.md"), "utf8").replace(`\`${BRAND.cli} rank\``, "`TAMPERED`"),
  );
  const third = renderDocs(root, { write: false });
  assert.ok(!third.ok, "a hand-edited generated block fails the check");
  assert.ok(third.files.some((f) => f.strict && f.why.includes("block commands-table")));
});

test("renderDocs on a root without markers manages nothing and stays ok (fixture safety)", () => {
  const root = dir();
  writeFileSync(join(root, "README.md"), "# plain fixture, hand-written table\n");
  const r = renderDocs(root, { write: false });
  assert.ok(r.ok, "no markers → nothing stale");
  assert.ok(
    r.missing.some((m) => m.name === "commands-table"),
    "absence is reported as informational",
  );
});
