#!/usr/bin/env node
/**
 * The claim/status registry, checked and rendered (node stdlib only).
 *
 * `docs/status/claims.json` records every load-bearing headline the project makes — what is
 * claimed, which component and version it is about, the commit it was assessed against, its
 * status, and the evidence behind it. This script keeps three things honest:
 *
 *   1. the registry itself: required fields, a closed set of statuses, unique ids, a commit
 *      that looks like one, and evidence paths that exist in the repository;
 *   2. the status table in `docs/status/README.md`, which is generated from the registry
 *      between the CLAIMS:BEGIN / CLAIMS:END markers and never edited by hand;
 *   3. the research copies under `docs/cognitive-substrate/`, which must stay byte-identical
 *      (sha256) to their canonical sources under `research/cognitive-substrate/`.
 *
 * Usage:
 *   node scripts/claims-status.mjs                  # validate, rewrite the table, check copies
 *   node scripts/claims-status.mjs --check          # validate + fail on any drift (CI mode)
 *   node scripts/claims-status.mjs --sync-copies    # re-copy canonical research files first
 *   node scripts/claims-status.mjs --root <dir>     # operate on another checkout
 *
 * Exit codes: 0 ok · 1 invalid registry or drift · 2 usage error.
 */
import { createHash } from "node:crypto";
import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

/** The closed set of statuses a claim may carry, in display order. */
export const STATUSES = ["implemented", "measured", "partial", "reported", "hypothesis", "refuted"];

/** Every claim must carry each of these fields. */
export const REQUIRED_FIELDS = [
  "id",
  "claim",
  "component",
  "version",
  "source_commit",
  "status",
  "evidence",
  "notes",
];

export const REGISTRY_PATH = "docs/status/claims.json";
export const README_PATH = "docs/status/README.md";
export const BEGIN = "<!-- CLAIMS:BEGIN (generated by scripts/claims-status.mjs — do not edit) -->";
export const END = "<!-- CLAIMS:END -->";

/**
 * Byte-identical copies kept under docs/ for readers there: [copy, canonical source].
 * `research/` is canonical; `--sync-copies` copies source → copy.
 * @type {ReadonlyArray<readonly [string, string]>}
 */
export const COPY_PAIRS = [
  [
    "docs/cognitive-substrate/cognitive_substrate_whitepaper.html",
    "research/cognitive-substrate/cognitive_substrate_whitepaper.html",
  ],
  [
    "docs/cognitive-substrate/cognitive_substrate_whitepaper.pdf",
    "research/cognitive-substrate/cognitive_substrate_whitepaper.pdf",
  ],
  [
    "docs/cognitive-substrate/evidence_map.md",
    "research/cognitive-substrate/evidence/evidence_map.md",
  ],
  [
    "docs/cognitive-substrate/ecosystem_map.md",
    "research/cognitive-substrate/evidence/ecosystem_map.md",
  ],
];

const ID_RE = /^[a-z0-9][a-z0-9-]*$/;
const COMMIT_RE = /^[0-9a-f]{7,40}$/;
const URL_RE = /^https?:\/\//;

const DEFAULT_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");

/**
 * Validate a parsed registry. Pure apart from optional evidence-path existence checks, which
 * run only when `root` is given.
 * @param {any} registry the parsed claims.json
 * @param {{root?: string|null}} [opts]
 * @returns {string[]} human-readable problems; empty means valid
 */
export function validateRegistry(registry, { root = null } = {}) {
  const errors = [];
  if (!registry || typeof registry !== "object" || Array.isArray(registry)) {
    return ["registry must be a JSON object with a `claims` array"];
  }
  if (!Array.isArray(registry.claims) || registry.claims.length === 0) {
    return ["registry.claims must be a non-empty array"];
  }
  const seen = new Set();
  registry.claims.forEach((c, i) => {
    const where = `claims[${i}]${c && typeof c.id === "string" ? ` (${c.id})` : ""}`;
    if (!c || typeof c !== "object" || Array.isArray(c)) {
      errors.push(`${where}: must be an object`);
      return;
    }
    for (const f of REQUIRED_FIELDS) {
      if (!(f in c)) errors.push(`${where}: missing required field "${f}"`);
    }
    for (const f of ["id", "claim", "component", "version", "source_commit", "status"]) {
      if (f in c && (typeof c[f] !== "string" || !c[f].trim())) {
        errors.push(`${where}: "${f}" must be a non-empty string`);
      }
    }
    if ("notes" in c && typeof c.notes !== "string") {
      errors.push(`${where}: "notes" must be a string`);
    }
    if (typeof c.id === "string" && c.id) {
      if (!ID_RE.test(c.id)) errors.push(`${where}: id must match ${ID_RE}`);
      if (seen.has(c.id)) errors.push(`${where}: duplicate id "${c.id}"`);
      seen.add(c.id);
    }
    if (typeof c.status === "string" && c.status && !STATUSES.includes(c.status)) {
      errors.push(`${where}: status "${c.status}" is not one of ${STATUSES.join(", ")}`);
    }
    if (typeof c.source_commit === "string" && c.source_commit) {
      if (!COMMIT_RE.test(c.source_commit)) {
        errors.push(`${where}: source_commit must be 7-40 lowercase hex characters`);
      }
    }
    if ("evidence" in c) {
      if (!Array.isArray(c.evidence) || c.evidence.length === 0) {
        errors.push(`${where}: evidence must be a non-empty array of paths or URLs`);
      } else {
        for (const e of c.evidence) {
          if (typeof e !== "string" || !e.trim()) {
            errors.push(`${where}: every evidence entry must be a non-empty string`);
            continue;
          }
          if (root && !URL_RE.test(e)) {
            const rel = e.split("#")[0];
            if (!existsSync(path.join(root, rel))) {
              errors.push(`${where}: evidence path not found: ${rel}`);
            }
          }
        }
      }
    }
  });
  return errors;
}

/** Escape a value for a single Markdown table cell. */
const cell = (s) =>
  String(s ?? "")
    .replace(/\r?\n/g, " ")
    .replace(/\|/g, "\\|")
    .trim();

/**
 * One evidence entry as a Markdown link: URLs keep their address; repository paths become
 * links relative to docs/status/README.md.
 * @param {string} e
 */
export function evidenceLink(e) {
  if (URL_RE.test(e)) {
    const label = e.replace(URL_RE, "").replace(/\/$/, "");
    return `[${cell(label)}](${e})`;
  }
  return `[\`${cell(e)}\`](../../${e})`;
}

/**
 * Render the generated block (without the markers): a status summary and one table row per
 * claim, in registry order.
 * @param {any} registry a valid registry
 * @returns {string}
 */
export function renderTable(registry) {
  const claims = registry.claims;
  const counts = STATUSES.map((s) => [s, claims.filter((c) => c.status === s).length]);
  const commits = [...new Set(claims.map((c) => c.source_commit))];
  const lines = [
    `${claims.length} claims — ${counts.map(([s, n]) => `${s} ${n}`).join(" · ")}.`,
    `Assessed against commit${commits.length > 1 ? "s" : ""} ${commits.map((c) => `\`${c.slice(0, 12)}\``).join(", ")}${registry.as_of ? ` (as of ${registry.as_of})` : ""}.`,
    "",
    "| ID | Status | Claim | Component · version | Evidence | Notes |",
    "| --- | --- | --- | --- | --- | --- |",
  ];
  for (const c of claims) {
    lines.push(
      `| \`${cell(c.id)}\` | **${cell(c.status)}** | ${cell(c.claim)} | ${cell(c.component)} · ${cell(c.version)} | ${c.evidence.map(evidenceLink).join("<br>")} | ${cell(c.notes)} |`,
    );
  }
  return lines.join("\n");
}

/**
 * Replace the generated block in the README text.
 * @param {string} text current README
 * @param {string} block rendered block (no markers)
 * @returns {string}
 */
export function spliceReadme(text, block) {
  const begin = text.indexOf(BEGIN);
  const end = text.indexOf(END);
  if (begin === -1 || end === -1 || end < begin) {
    throw new Error(`${README_PATH} must contain the markers ${BEGIN} … ${END}`);
  }
  return `${text.slice(0, begin)}${BEGIN}\n${block}\n${text.slice(end)}`;
}

/** @param {string} file */
export const sha256File = (file) => createHash("sha256").update(readFileSync(file)).digest("hex");

/**
 * Compare each docs copy with its canonical source.
 * @param {string} root
 * @param {ReadonlyArray<readonly [string, string]>} [pairs]
 * @returns {{copy: string, source: string, ok: boolean, reason: string}[]}
 */
export function checkCopies(root, pairs = COPY_PAIRS) {
  return pairs.map(([copy, source]) => {
    const c = path.join(root, copy);
    const s = path.join(root, source);
    if (!existsSync(s)) return { copy, source, ok: false, reason: "canonical source missing" };
    if (!existsSync(c)) return { copy, source, ok: false, reason: "copy missing" };
    const same = sha256File(c) === sha256File(s);
    return { copy, source, ok: same, reason: same ? "identical" : "sha256 differs" };
  });
}

/**
 * Copy every drifted canonical source over its docs copy.
 * @param {string} root
 * @param {ReadonlyArray<readonly [string, string]>} [pairs]
 * @returns {string[]} the copies rewritten
 */
export function syncCopies(root, pairs = COPY_PAIRS) {
  const written = [];
  for (const r of checkCopies(root, pairs)) {
    if (r.ok || r.reason === "canonical source missing") continue;
    copyFileSync(path.join(root, r.source), path.join(root, r.copy));
    written.push(r.copy);
  }
  return written;
}

/**
 * The CLI. Returns an exit code instead of exiting, so tests can drive it.
 * @param {string[]} argv
 * @param {{root?: string, pairs?: ReadonlyArray<readonly [string, string]>,
 *          log?: (s: string) => void, error?: (s: string) => void}} [io]
 * @returns {number}
 */
export function run(argv, io = {}) {
  const log = io.log ?? ((s) => process.stdout.write(`${s}\n`));
  const error = io.error ?? ((s) => process.stderr.write(`${s}\n`));
  let root = io.root ?? DEFAULT_ROOT;
  const pairs = io.pairs ?? COPY_PAIRS;
  const flags = new Set();
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === "--root") {
      const next = argv[++i];
      if (!next) {
        error("--root needs a directory");
        return 2;
      }
      root = path.resolve(next);
    } else if (a === "--check" || a === "--sync-copies") flags.add(a);
    else if (a === "--help" || a === "-h") {
      log(
        "usage: node scripts/claims-status.mjs [--check] [--sync-copies] [--root <dir>]\n" +
          "  (no flag)      validate the registry, rewrite the table in docs/status/README.md, check copies\n" +
          "  --check        validate and fail (exit 1) on a stale table or a drifted docs copy\n" +
          "  --sync-copies  copy canonical research/ files over drifted docs/ copies first",
      );
      return 0;
    } else {
      error(`unknown argument: ${a}`);
      return 2;
    }
  }
  const check = flags.has("--check");

  let registry;
  try {
    registry = JSON.parse(readFileSync(path.join(root, REGISTRY_PATH), "utf8"));
  } catch (e) {
    error(`cannot read ${REGISTRY_PATH}: ${/** @type {Error} */ (e).message}`);
    return 1;
  }
  const problems = validateRegistry(registry, { root });
  if (problems.length) {
    for (const p of problems) error(`registry: ${p}`);
    return 1;
  }

  let failed = false;
  const readmeFile = path.join(root, README_PATH);
  let current;
  try {
    // Compare line content, not line endings: a Windows checkout (core.autocrlf) has CRLF.
    current = readFileSync(readmeFile, "utf8").replace(/\r\n/g, "\n");
  } catch (e) {
    error(`cannot read ${README_PATH}: ${/** @type {Error} */ (e).message}`);
    return 1;
  }
  let expected;
  try {
    expected = spliceReadme(current, renderTable(registry));
  } catch (e) {
    error(/** @type {Error} */ (e).message);
    return 1;
  }
  if (expected !== current) {
    if (check) {
      error(`${README_PATH} is stale — run \`node scripts/claims-status.mjs\` to regenerate it`);
      failed = true;
    } else {
      writeFileSync(readmeFile, expected);
      log(`rewrote the generated table in ${README_PATH}`);
    }
  }

  if (flags.has("--sync-copies") && !check) {
    for (const c of syncCopies(root, pairs)) log(`re-copied ${c} from its canonical source`);
  }
  for (const r of checkCopies(root, pairs)) {
    if (!r.ok) {
      error(`copy drift: ${r.copy} vs ${r.source} — ${r.reason} (run with --sync-copies)`);
      failed = true;
    }
  }

  if (failed) return 1;
  log(
    `ok: ${registry.claims.length} claims valid, ${README_PATH} current, ${pairs.length} docs copies identical`,
  );
  return 0;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  process.exit(run(process.argv.slice(2)));
}
