// forge docs render — the docs write themselves where they can. docs_check.js can only
// DETECT drift between the registries and the prose; every fix was still a human
// hand-editing tables in five files. This module closes the loop: the derivable parts
// of the docs (command tables, the MCP tool table, the "N MCP tools" count phrases, the
// mermaid theme, the repo map) are RENDERED from the same registries the check reads —
// COMMANDS/GROUPS, mcp_tools.TOOLS, brand.json, the live import graph — into
// marker-managed blocks, exactly the pattern bench/bench.mjs already uses for
// reports/benchmarks.md. Prose stays human; tables and diagrams become machine-owned.
// `forge docs render` regenerates; `--check` (and the docs-check reconciler) fails CI
// with the exact command to run, so "docs out of sync" becomes a one-command repair.
//
// Registry-derived blocks (tables, counts) are enforced as ERRORS; tree-derived output
// (the repo-map diagram, mermaid theme normalization) is advisory — a moved file should
// not fail an unrelated PR, but a new command with a stale table must.
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { BRAND } from "./brand.js";
import { commandSummary, GROUPS } from "./commands.js";
import { TOOLS } from "./mcp_tools.js";
import { directedImportGraph } from "./scope.js";
import { git } from "./util.js";

const BEGIN = (name) =>
  `<!-- forge:render:${name}:begin (generated by \`${BRAND.cli} docs render\` — do not edit) -->`;
const END = (name) => `<!-- forge:render:${name}:end -->`;

/** Pad a markdown table so the raw text stays readable (the repo's tables are aligned). */
function mdTable(headers, rows) {
  const all = [headers, ...rows];
  const width = headers.map((_, i) => Math.max(...all.map((r) => String(r[i]).length)));
  const line = (r) => `| ${r.map((c, i) => String(c).padEnd(width[i])).join(" | ")} |`;
  const rule = `| ${width.map((w) => "-".repeat(w)).join(" | ")} |`;
  return [line(headers), rule, ...rows.map(line)].join("\n");
}

/**
 * One mermaid theme for every diagram, derived from brand.json (never hardcoded hexes) —
 * change the brand, run `forge docs render`, every diagram re-themes. Carries the two
 * load-bearing identity hexes docs_check requires (brand → lineColor, bg → tertiaryColor)
 * plus the readability settings the hand-written init strings never had.
 */
export function mermaidInit() {
  const d = BRAND.colors?.dark ?? {};
  const vars = [
    `'primaryColor':'${d["bg-2"]}'`,
    `'primaryTextColor':'${d.text}'`,
    `'primaryBorderColor':'${d.line}'`,
    `'lineColor':'${d.brand}'`,
    `'secondaryColor':'${d["panel-2"]}'`,
    `'tertiaryColor':'${d.bg}'`,
    `'edgeLabelBackground':'${d["bg-2"]}'`,
    `'clusterBkg':'${d.bg}'`,
    `'clusterBorder':'${d["line-strong"]}'`,
    `'fontFamily':'ui-sans-serif, system-ui, sans-serif'`,
    `'fontSize':'14px'`,
  ].join(",");
  const layout = `'flowchart':{'curve':'basis','padding':10,'nodeSpacing':36,'rankSpacing':44}`;
  return `%%{init: {'theme':'base','themeVariables':{${vars}},${layout}}}%%`;
}

/** The README command table — one row per command, grouped exactly like `--help`. */
export function renderCommandsTable() {
  const rows = [];
  for (const [group, names] of Object.entries(GROUPS)) {
    names.forEach((name, i) => {
      rows.push([i === 0 ? `**${group}**` : "", `\`${BRAND.cli} ${name}\``, commandSummary(name)]);
    });
  }
  return mdTable(["Group", "Command", "Does"], rows);
}

/** The GUIDE group map — same grouping as `--help`, one row per group. */
export function renderGroupsTable() {
  const rows = Object.entries(GROUPS).map(([group, names]) => [
    `**${group}**`,
    names.map((n) => `\`${BRAND.cli} ${n}\``).join(" · "),
  ]);
  return mdTable(["Group", "Commands"], rows);
}

/** The MCP tool table — straight from the TOOLS registry, first sentence per tool. */
export function renderMcpToolsTable() {
  const firstSentence = (s) => {
    const cut = s.indexOf(". ");
    return (cut > 0 ? s.slice(0, cut + 1) : s).trim();
  };
  return mdTable(
    ["MCP tool", "Does"],
    TOOLS.map((t) => [`\`${t.name}\``, firstSentence(t.description)]),
  );
}

/**
 * The repo map: top-level directories sized by file count, edges = import counts between
 * them, from the live import graph (scope.directedImportGraph). Deterministic ordering.
 * @param {string} root
 * @param {{maxDirs?:number}} [opts]
 */
export function renderRepoMap(root, { maxDirs = 9 } = {}) {
  const g = directedImportGraph(root);
  const dirOf = (f) => (f.includes("/") ? f.slice(0, f.indexOf("/")) : "(root)");
  const files = new Map(); // dir → count
  for (const f of g.nodes) files.set(dirOf(f), (files.get(dirOf(f)) ?? 0) + 1);
  const kept = [...files.entries()]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .slice(0, maxDirs)
    .map(([dir]) => dir);
  const keptSet = new Set(kept);
  const edges = new Map(); // "a→b" → count
  for (const [from, targets] of [...g.edges.entries()].sort((a, b) => a[0].localeCompare(b[0]))) {
    for (const to of [...targets].sort()) {
      const a = dirOf(from);
      const b = dirOf(to);
      if (a === b || !keptSet.has(a) || !keptSet.has(b)) continue;
      const key = `${a}→${b}`;
      edges.set(key, (edges.get(key) ?? 0) + 1);
    }
  }
  const id = (dir) => dir.replace(/[^A-Za-z0-9]/g, "_");
  const lines = [mermaidInit(), "flowchart LR"];
  for (const dir of kept)
    lines.push(
      `  ${id(dir)}["${dir}<br/>${files.get(dir)} file${files.get(dir) === 1 ? "" : "s"}"]`,
    );
  for (const [key, n] of [...edges.entries()].sort(
    (a, b) => b[1] - a[1] || a[0].localeCompare(b[0]),
  )) {
    const [a, b] = key.split("→");
    lines.push(`  ${id(a)} ${n > 1 ? `-- ${n} --> ` : "--> "}${id(b)}`);
  }
  return `\`\`\`mermaid\n${lines.join("\n")}\n\`\`\``;
}

/** Replace one managed block. Returns the new text plus whether markers were found/changed. */
export function spliceBlock(text, name, body) {
  const begin = text.indexOf(BEGIN(name));
  const end = text.indexOf(END(name));
  if (begin === -1 || end === -1 || end < begin) return { text, found: false, changed: false };
  const next = `${text.slice(0, begin)}${BEGIN(name)}\n${body}\n${text.slice(end)}`;
  return { text: next, found: true, changed: next !== text };
}

/** Rewrite every literal "N MCP tools" phrase to the registry's real count. */
export function updateCounts(text) {
  return text.replace(/\b\d+ MCP tools\b/g, `${TOOLS.length} MCP tools`);
}

const MERMAID_BLOCK_RE = /```mermaid\n([\s\S]*?)```/g;
const INIT_LINE_RE = /%%\{init[\s\S]*?\}%%/;

/** Normalize every mermaid block's `%%{init` line to the one shared brand theme.
 *  Blocks opted out with `docs-check-ignore` (deliberate bad examples) are untouched;
 *  blocks with no init line are left for docs_check to flag. */
export function normalizeMermaid(text) {
  return text.replace(MERMAID_BLOCK_RE, (block, body, offset) => {
    if (/docs-check-ignore/.test(text.slice(Math.max(0, offset - 80), offset))) return block;
    if (!INIT_LINE_RE.test(body)) return block;
    return block.replace(INIT_LINE_RE, mermaidInit());
  });
}

// Which generated block lives in which file. Registry-derived blocks are ERRORS when
// stale (a new command MUST regenerate); the tree-derived repo map is advisory.
const BLOCK_TARGETS = [
  {
    file: "README.md",
    name: "commands-table",
    render: () => renderCommandsTable(),
    strict: true,
  },
  {
    file: "docs/GUIDE.md",
    name: "command-groups",
    render: () => renderGroupsTable(),
    strict: true,
  },
  {
    file: "docs/GUIDE.md",
    name: "mcp-tools",
    render: () => renderMcpToolsTable(),
    strict: true,
  },
  {
    file: "ARCHITECTURE.md",
    name: "repo-map",
    render: (root) => renderRepoMap(root),
    strict: false,
  },
];

// Files whose "N MCP tools" phrases are auto-corrected (the six the count lives in).
const COUNT_FILES = [
  "README.md",
  "docs/GUIDE.md",
  "ARCHITECTURE.md",
  "ROADMAP.md",
  "mintlify/quickstart.mdx",
  "mintlify/concepts/config-compiler.mdx",
];

/** Every git-tracked markdown file (mermaid theme normalization scope). */
function trackedMarkdown(root) {
  const out = git(root, ["ls-files", "*.md"]);
  return out ? out.split("\n").filter(Boolean) : [];
}

/**
 * Render every managed doc surface. With {write:true} stale files are rewritten;
 * otherwise this is a pure report (what `--check` and the docs-check reconciler use).
 * @param {string} [root]
 * @param {{write?: boolean}} [opts]
 * @returns {{ok:boolean, files:{file:string, changed:boolean, strict:boolean, why:string[]}[],
 *   missing:{file:string, name:string}[]}}
 */
export function renderDocs(root = BRAND.root, { write = false } = {}) {
  /** @type {Map<string, {text:string, orig:string, strict:boolean, why:string[]}>} */
  const touched = new Map();
  const missing = [];
  const load = (file) => {
    if (!touched.has(file)) {
      let text;
      try {
        text = readFileSync(join(root, file), "utf8");
      } catch {
        return null;
      }
      touched.set(file, { text, orig: text, strict: false, why: [] });
    }
    return touched.get(file);
  };

  for (const t of BLOCK_TARGETS) {
    const doc = load(t.file);
    if (!doc) continue;
    if (doc.text.indexOf(BEGIN(t.name)) === -1) {
      // No markers → nothing to manage here (fixture roots, forks that opted out).
      // Don't render (the repo map walks the tree) and don't flag — the registry
      // reconcilers still cover the content the old hand-written way.
      missing.push({ file: t.file, name: t.name });
      continue;
    }
    const r = spliceBlock(doc.text, t.name, t.render(root));
    if (!r.found) {
      missing.push({ file: t.file, name: t.name });
      continue;
    }
    if (r.changed) {
      doc.why.push(`block ${t.name}`);
      if (t.strict) doc.strict = true;
    }
    doc.text = r.text;
  }
  for (const file of COUNT_FILES) {
    const doc = load(file);
    if (!doc) continue;
    const next = updateCounts(doc.text);
    if (next !== doc.text) {
      doc.why.push("MCP tool count");
      doc.strict = true;
      doc.text = next;
    }
  }
  for (const file of trackedMarkdown(root)) {
    const doc = load(file);
    if (!doc) continue;
    const next = normalizeMermaid(doc.text);
    if (next !== doc.text) {
      doc.why.push("mermaid theme");
      doc.text = next;
    }
  }

  const files = [];
  for (const [file, doc] of touched) {
    const changed = doc.text !== doc.orig;
    if (changed && write) writeFileSync(join(root, file), doc.text);
    if (changed || doc.why.length) files.push({ file, changed, strict: doc.strict, why: doc.why });
  }
  // `missing` is informational (a root without markers manages nothing) — only STALE
  // strict surfaces fail the check.
  return { ok: files.every((f) => !f.strict), files, missing };
}
