// Shared helpers for emitters. Every generated file carries a `forge:sync:<hash>`
// marker so re-running is idempotent (skip identical content) and drift is
// detectable (forge doctor compares the marker to the current source hash).
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export const MARKER = "forge:sync";

export const hashContent = (str) => createHash("sha256").update(str).digest("hex").slice(0, 12);

export const markerString = (hash) => `${MARKER}:${hash}`;

export const mdHeader = (hash) =>
  `<!-- GENERATED by \`forge sync\` — edit source/rules.json, not this file. ${markerString(hash)} -->`;

export const yamlHeader = (hash) =>
  `# GENERATED by \`forge sync\` — edit source/rules.json, not this file. ${markerString(hash)}`;

export const readIfExists = (p) => (existsSync(p) ? readFileSync(p, "utf8") : null);

export const isManaged = (text) => typeof text === "string" && text.includes(`${MARKER}:`);

export function extractHash(text) {
  const m = typeof text === "string" && text.match(new RegExp(`${MARKER}:([a-f0-9]{12})`));
  return m ? m[1] : null;
}

// Write only when the file BODY differs from what's on disk. Comparing the full expected
// content (not just the embedded marker hash) means a hand-edited body with an intact marker
// is detected and restored — the marker alone can't be trusted as proof of sync (P0-08).
export function writeIfChanged(absPath, content) {
  const existing = readIfExists(absPath);
  if (existing === content) return "unchanged";
  mkdirSync(dirname(absPath), { recursive: true });
  writeFileSync(absPath, content);
  return "written";
}

export const writeManaged = (absPath, header, body) =>
  writeIfChanged(absPath, `${header}\n${body}\n`);
