// Shared helpers for emitters. Every generated file carries a `forge:sync:<hash>`
// marker so re-running is idempotent (skip identical content) and drift is
// detectable (forge doctor compares the marker to the current source hash).
import { createHash } from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

export const MARKER = "forge:sync";

export const hashContent = (str) => createHash("sha256").update(str).digest("hex").slice(0, 12);

export const markerString = (hash) => `${MARKER}:${hash}`;

export const mdHeader = (hash) =>
  `<!-- GENERATED by \`forge sync\` — edit source/rules.json, not this file. ${markerString(hash)} -->`;

export const yamlHeader = (hash) =>
  `# GENERATED by \`forge sync\` — edit source/rules.json, not this file. ${markerString(hash)}`;

export const readIfExists = (p) => (existsSync(p) ? readFileSync(p, "utf8") : null);

export const isManaged = (text) => typeof text === "string" && text.includes(`${MARKER}:`);

export function extractHash(text) {
  const m = typeof text === "string" && text.match(new RegExp(`${MARKER}:([a-f0-9]{12})`));
  return m ? m[1] : null;
}

// Write only when the file BODY differs from what's on disk. Comparing the full expected
// content (not just the embedded marker hash) means a hand-edited body with an intact marker
// is detected and restored — the marker alone can't be trusted as proof of sync (P0-08).
export function writeIfChanged(absPath, content) {
  const existing = readIfExists(absPath);
  if (existing === content) return "unchanged";
  mkdirSync(dirname(absPath), { recursive: true });
  writeFileSync(absPath, content);
  return "written";
}

// The exact on-disk bytes of a managed file. BOTH the writer (writeManaged) and any
// drift check (autoSyncIfDrifted) must build the expectation through this one helper —
// comparing anything less than these full bytes (e.g. only the embedded marker hash)
// lets a hand-edited body with an intact marker pass as "in sync" (RA-16).
export const managedContent = (header, body) => `${header}\n${body}\n`;

export const writeManaged = (absPath, header, body) =>
  writeIfChanged(absPath, managedContent(header, body));

// ---------------------------------------------------------------------------
// Managed BLOCK: how forge owns PART of a file a human also writes (AGENTS.md). Forge
// rewrites only the lines between the two markers; everything outside them belongs to
// the human and is never rewritten, reordered or dropped.
// ---------------------------------------------------------------------------

const MARKER_NS = MARKER.split(":")[0];
export const BLOCK_BEGIN = `<!-- ${MARKER_NS}:begin -->`;
export const BLOCK_END = `<!-- ${MARKER_NS}:end -->`;

/** A marker counts only as a whole line, so prose that mentions it inline is never taken
 *  for the block. `\r?` tolerates a CRLF checkout. */
const wholeLine = (marker) => new RegExp(`^${marker}\\r?$`, "m");
const BEGIN_RE = wholeLine(BLOCK_BEGIN);
const END_RE = wholeLine(BLOCK_END);

/** A body line that reads exactly like a marker (a multi-line rule, fact or lesson can hold
 *  one) would end the block early: every sync would then see drift and leave another stale
 *  tail behind, growing the file. Such a line is indented one space, which Markdown renders
 *  the same and which no longer matches a whole-line marker. */
const MARKER_LINE_RE = new RegExp(`^(?:${BLOCK_BEGIN}|${BLOCK_END})\\r?$`, "gm");

/** The exact bytes of the managed block: begin marker, the generated header (it carries the
 *  `forge:sync:<hash>` marker), the body, end marker. The writer and every drift check build
 *  their expectation through this one helper, as with managedContent (RA-16). */
export const managedBlock = (header, body) =>
  `${BLOCK_BEGIN}\n${header}\n${body.replace(MARKER_LINE_RE, " $&").replace(/\n*$/, "\n")}${BLOCK_END}\n`;

/**
 * Locate the managed block. null when there is none; `{damaged: true}` when only one marker
 * is present or the end comes first (forge must not guess where its text stops); otherwise
 * the extent `[start, end)`, where `end` includes the end marker's newline.
 * @param {string|null} text
 * @returns {null | {damaged: true} | {damaged: false, start: number, end: number}}
 */
export function findManagedBlock(text) {
  if (typeof text !== "string") return null;
  const begin = BEGIN_RE.exec(text);
  const anyEnd = END_RE.exec(text);
  if (!begin && !anyEnd) return null;
  if (!begin) return { damaged: true };
  const from = begin.index + begin[0].length;
  const end = END_RE.exec(text.slice(from));
  if (!end) return { damaged: true };
  let stop = from + end.index + end[0].length;
  if (text[stop] === "\n") stop += 1;
  return { damaged: false, start: begin.index, end: stop };
}

/** True iff the text holds a complete (begin + end) forge-managed block. */
export function hasManagedBlock(text) {
  const b = findManagedBlock(text);
  return Boolean(b && !b.damaged);
}

/** The generated-header line (any hash) — how a pre-block, fully generated file starts, and
 *  the line an adopted file's marker is refreshed through in place. */
export const MD_HEADER_RE = new RegExp(
  `^<!-- GENERATED by .*${MARKER}:([a-f0-9]{12}) -->[ \\t]*\\r?$`,
  "m",
);

/**
 * Split a legacy fully generated file (the pre-block format: `mdHeader` line, then the body)
 * into the human text around forge's region. The header's hash is the hash of the body forge
 * wrote, so the split whose body hashes to it is forge's text byte for byte: whatever sits
 * above the header or below that body was added by a person and is returned verbatim.
 * `lossless: false` means no split matched (the generated region itself was edited), so
 * forge cannot tell its bytes from the person's and the caller must keep a backup.
 * @param {string|null} text
 * @returns {null | {lossless: boolean, before: string, after: string}}
 */
export function splitLegacyManaged(text) {
  if (typeof text !== "string" || findManagedBlock(text)) return null;
  const m = MD_HEADER_RE.exec(text);
  if (!m) return null;
  const before = text.slice(0, m.index);
  let rest = text.slice(m.index + m[0].length);
  if (rest.startsWith("\n")) rest = rest.slice(1);
  // managedContent wrote `${header}\n${body}\n` and a body always ends in "\n", so forge's
  // region ends at a blank line: test only those (one sha256 each, a few dozen at most).
  for (let k = rest.indexOf("\n\n") + 1; k > 0; k = rest.indexOf("\n\n", k) + 1) {
    if (hashContent(rest.slice(0, k)) === m[1])
      return { lossless: true, before, after: rest.slice(k + 1) };
  }
  return { lossless: false, before, after: "" };
}
